<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita4ad9c5c0cd11955cc68a9bf970f730f
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita4ad9c5c0cd11955cc68a9bf970f730f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita4ad9c5c0cd11955cc68a9bf970f730f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInita4ad9c5c0cd11955cc68a9bf970f730f::$classMap;

        }, null, ClassLoader::class);
    }
}
